# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QAction, qApp, QPushButton, QLineEdit, QInputDialog
from PyQt5.QtGui import QIcon
import pandas as pd
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from threading import Timer
import time
import calendar
from PyQt5 import *
from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser
import information

#메인 UI

class Ui_MainWindow(QMainWindow):
    name = ''
    type1 = ''
    amount = ''
    Date = 0

    serch_name = ''
    serch_date = 0
    investtype = 0
    _window2 =None


    def __init__(self,_window2=None):
        super(Ui_MainWindow,self).__init__()
        self._window2 = _window2



        self.year = int()
        self.month = int()
        self.day = int()
        self.hour = int()
        self.min = int()
        self.sec = int()
        self.wDay = int()
        self.week = ['월','화','수','목','금','토','일']
        self.workweek = ['월','화','수','목','금']
        self.Datecountstr = ''






    def setupUi(self, MainWindow):
        self.showtime()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 800)
        MainWindow.setAcceptDrops(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 291, 71))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 28pt \"Adobe Arabic\";")
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 30, 101, 41))
        self.pushButton.setObjectName("pushButton")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 331, 41))
        self.label_2.setObjectName("label_2")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(0, 130, 101, 16))
        self.checkBox.setObjectName("checkBox")

        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 130, 91, 16))
        self.checkBox_2.setObjectName("checkBox_2")

        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(190, 130, 91, 16))
        self.checkBox_3.setObjectName("checkBox_3")

        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 130, 91, 16))
        self.checkBox_4.setObjectName("checkBox_4")

        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(370, 130, 101, 16))
        self.checkBox_5.setObjectName("checkBox_5")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 170, 331, 51))
        self.label_3.setStyleSheet("font: 28pt \"Adobe Caslon Pro\";")
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 160, 701, 16))
        self.label_4.setObjectName("label_4")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 240, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 220, 121, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 220, 91, 16))
        self.label_6.setObjectName("label_6")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 240, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 220, 81, 16))
        self.label_7.setObjectName("label_7")

        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(280, 240, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 170, 181, 16))
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(420, 220, 56, 12))
        self.label_9.setObjectName("label_9")

        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(420, 240, 91, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 600, 81, 16))
        self.label_10.setObjectName("label_10")

        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(0, 640, 500, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0, 310, 121, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(120, 310, 121, 16))
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 310, 121, 16))
        self.label_13.setObjectName("label_13")

        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(420, 310, 121, 16))
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(0, 500, 121, 16))
        self.label_19.setObjectName("label_19")

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(130, 400, 121, 16))
        self.label_20.setObjectName("label_20")

        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(260, 400, 121, 16))
        self.label_21.setObjectName("label_21")

        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(400, 400, 121, 16))
        self.label_22.setObjectName("label_22")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 670, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")

        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(0, 330, 76, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")

        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(120, 330, 76, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")

        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(270, 330, 76, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")

        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setGeometry(QtCore.QRect(420, 330, 111, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")

        self.comboBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_10.setGeometry(QtCore.QRect(0, 520, 200, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")

        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(130, 420, 91, 22))
        self.spinBox.setObjectName("spinBox")

        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(250, 420, 91, 22))
        self.spinBox_2.setObjectName("spinBox_2")

        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(400, 420, 91, 22))
        self.spinBox_3.setObjectName("spinBox_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "미래 에셋 생명"))

        self.label.setText(_translate("MainWindow", "투자 성향 검색"))

        self.pushButton.setText(_translate("MainWindow", "검색"))
        self.pushButton.clicked.connect(lambda : webbrowser.open('https://securities.miraeasset.com/hku/hku4128/c01.do'))



        self.label_2.setText(_translate("MainWindow", "검색 후 선택해주세요!!"))

        self.checkBox.setText(_translate("MainWindow", "1등급 초고위험"))
        self.checkBox_2.setText(_translate("MainWindow", "2등급 고위험"))
        self.checkBox_3.setText(_translate("MainWindow", "3등급 중위험"))
        self.checkBox_4.setText(_translate("MainWindow", "4등급 저위험"))
        self.checkBox_5.setText(_translate("MainWindow", "5등급 초저위험"))
        self.checkBox.stateChanged.connect(lambda : self.invest_type(5))
        self.checkBox_2.stateChanged.connect(lambda :self.invest_type(4))
        self.checkBox_3.stateChanged.connect(lambda :self.invest_type(3))
        self.checkBox_4.stateChanged.connect(lambda :self.invest_type(2))
        self.checkBox_5.stateChanged.connect(lambda :self.invest_type(1))



        self.label_3.setText(_translate("MainWindow", "계약 정보"))

        self.label_4.setText(_translate("MainWindow", "---------------------------------------------------------------------------------------------------------------------"))

        self.comboBox.setItemText(0, _translate("MainWindow", "변액 연금 보험"))
        self.comboBox.setItemText(1, _translate("MainWindow", "변액 유니버셜 보험"))


        self.label_5.setText(_translate("MainWindow", "상품 구분*"))

        self.label_6.setText(_translate("MainWindow", "나이*"))

        self.comboBox_2.setItemText(0, _translate("MainWindow", "0~19세"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "20~35세"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "36~40세"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "41~55세"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "56~70세"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "71세 이상"))

        self.label_7.setText(_translate("MainWindow", "채널 구분*"))

        self.comboBox_3.setItemText(0, _translate("MainWindow", "보험 설계사"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "GA영업지점"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "방카"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "온라인"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "없음"))

        self.label_8.setText(_translate("MainWindow", ""))

        self.label_9.setText(_translate("MainWindow", "성별*"))

        self.comboBox_4.setItemText(0, _translate("MainWindow", "남성"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "여성"))

        self.label_10.setText(_translate("MainWindow", "직업*"))

        self.comboBox_5.setItemText(0, _translate("MainWindow", "사무관리직, 전문직, 공무원"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "제조업 현장 관리자"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "자영업자, 주부, 직업군인, 일반서비스업 종사자, 영업사원,제조업 현장 직업자"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "보험 설계사, 학생, 의료직 종사자, 프리랜서"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "위험직군, 운수직종, 계절적 휴업자, 건설/토목 종사자, 금속/화학 종사자"))

        self.label_11.setText(_translate("MainWindow", "약관 대출 여부*"))

        self.label_12.setText(_translate("MainWindow", "특약 여부*"))

        self.label_13.setText(_translate("MainWindow", "보험 보유 계약 건수*"))

        self.label_18.setText(_translate("MainWindow", "납입 주기*"))

        self.label_19.setText(_translate("MainWindow", "수금 방법*"))

        self.label_20.setText(_translate("MainWindow", "최종 납입 횟수"))

        self.label_21.setText(_translate("MainWindow", "가입 금액"))

        self.label_22.setText(_translate("MainWindow", "월납 보험료"))

        self.pushButton_2.setText(_translate("MainWindow", "확인"))
        self.pushButton_2.clicked.connect(self.check)





        self.comboBox_6.setItemText(0, _translate("MainWindow", "있음"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "없음"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "있음"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "없음"))

        self.comboBox_8.setItemText(0, _translate("MainWindow", "0개"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "1개"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "2개"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "3개"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "4개이상"))

        self.comboBox_9.setItemText(0, _translate("MainWindow", "일시납"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "월납"))

        self.comboBox_10.setItemText(0, _translate("MainWindow", "소극적 수금(방문 수금, 지로)"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "적극적 수금(자동이체, 카드이체)"))

        self.menu.setTitle(_translate("MainWindow", "미래 에셋 생명"))

    def invest_type(self,num):
        if num == 5:
            check =self.checkBox.isChecked()
            if check == True:
                self.investtype = num
        elif num == 4 :
            check = self.checkBox_2.isChecked()
            if check == True:
                self.investtype = num
        elif num == 3:
            check = self.checkBox_3.isChecked()
            if check == True:
                self.investtype = num
        elif num ==2:
            check = self.checkBox_4.isChecked()
            if check == True:
                self.investtype = num
        elif num == 1:
            check = self.checkBox_5.isChecked()
            if check == True:
                self.investtype = num

    def check(self):
        #information에서 2번째 UI제작 완료 하지만 두개의 layout 연동에 차질이 있음
        print('information에서 2번째 UI제작 완료 하지만 두개의 layout 연동에 차질이 있음')














    def showtime(self):
        lastday = ''



        date = QDate.currentDate()
        time = QTime.currentTime()

        # LCD 표시

        self.year = date.year()
        self.month=date.month()
        self.day=date.day()
        self.hour=time.hour()
        self.min=time.minute()
        self.sec=time.second()
        self.wDay=date.dayOfWeek()

        self.Datecountstr = str(self.year) + ' - '+ str(self.month) + ' - ' + str(self.day) + ' : ' + str(self.hour) + ' : ' + str(self.min) + ' : ' + str(self.sec) + '     '+str(self.week[self.wDay-1])
        self.statusBar().showMessage(self.Datecountstr)

        print(self.Datecountstr)

        # 타이머 설정  (1초마다, 콜백함수)
        end_month = calendar.monthrange(self.year, self.month)[1]
        timer = Timer(1, self.showtime)
        timer.start()


#information.py에 있는 class를 가져온 것 뿐입니다
#화면을 보고 싶으시면 information.py 실행해주세요
class second(QMainWindow):
    style=0
    product = 0
    age =0
    channel =0
    gender =0
    loan =0
    special =0
    insurance =0
    send =0
    final_send =0
    send_adduser =0
    month_send =0
    send_way =0
    job =0
    moreinfo =0
    def __init__(self):
        super(second,self).__init__()
        self.setupUi()
        self.retranslateUi()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 481, 61))
        self.label_3.setStyleSheet("font: 57 28pt \"Adobe 명조 Std M\";")
        self.label_3.setObjectName("label_3")
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(0, 60, 901, 721))
        self.tableView_2.setObjectName("tableView_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 10, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 20, 411, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "미래 에셋 생명"))

        self.label_3.setText(_translate("MainWindow", "추천 펀드"))

        self.pushButton.setText(_translate("MainWindow", "확인"))
        self.comboBox.setItemText(0, _translate("MainWindow", "펀드 평균 수익률"))
        self.comboBox.setItemText(1, _translate("MainWindow", "펀드 수익률 최소값"))
        self.comboBox.setItemText(2, _translate("MainWindow", "펀드 수익률 1분위 값"))
        self.comboBox.setItemText(3, _translate("MainWindow", "펀드 수익률 중간값"))
        self.comboBox.setItemText(4, _translate("MainWindow", "펀드 수익률 3분위 값"))
        self.comboBox.setItemText(5, _translate("MainWindow", "펀드 수익률 최댓 값"))
        self.menu.setTitle(_translate("MainWindow", "미래 에셋 생명"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())