데이터 셋 형태 확인

In [ ]:
import pandas as pd
import ast





#데이터 확인


Train = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(학습용데이터).csv', encoding='euc=kr')
Test = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(제출용데이터).csv', encoding='euc=kr')

#feature_group_A => x
data = ast.literal_eval(Train['Feature_Group_A'][0])
print(len(data))

#feature_group_B => y
data = ast.literal_eval(Train['Feature_Group_B'][0])
print(len(data))

#feature_group_C => z

#feature_group_C는 데이터가 str형태라서 딕셔너리로 변환하는 코드
data = ast.literal_eval(Train['Feature_Group_C'][0])
#딕셔너리 형태 'numstrings': 3312, 'avlength': 24.9393115942029, 'printabledist': [5963, 67, 449, 124, 398, 49, 90, 154, 326, 218, 65, 103, 491, 306, 802, 451, 1097, 727, 615, 602, 712, 633, 589, 508, 638, 529, 668, 759, 853, 531, 687, 738, 1020, 1084, 294, 733, 760, 831, 427, 336, 383, 782, 113, 83, 612, 327, 376, 542, 1055, 289, 527, 812, 883, 489, 558, 658, 314, 283, 145, 103, 223, 91, 99, 412, 244, 3157, 869, 1713, 1846, 5152, 913, 973, 1322, 2815, 321, 306, 2263, 990, 3001, 3620, 1423, 200, 3392, 2378, 4119, 1238, 438, 985, 806, 851, 113, 123, 181, 100, 75, 86], 'printables': 82599, 'entropy': 5.8347296238951945, 'paths': 0, 'urls': 39, 'registry': 0, 'MZ': 8
print(len(data['printabledist']))
print(type(data['numstrings']))
print(type(data['avlength']))
print(type(data['printables']))




256
256
96
<class 'int'>
<class 'float'>
<class 'int'>


In [ ]:
#차원 축소

**3AutoML 모델 이용**

https://colab.research.google.com/github/rpi-techfundamentals/spring2019-materials/blob/master/14-automl/01_auto_ml_tpot.ipynb#scrollTo=uhBlHuGpO2n6



In [ ]:
# Install tpot on the server
!pip install tpot
!pip install -U scikit-learn

     |████████████████████████████████| 87 kB 5.1 MB/s 
     |████████████████████████████████| 160 kB 40.3 MB/s 
     |████████████████████████████████| 173.5 MB 14 kB/s 
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11952 sha256=e6c946d9b1349c68afa0120a3eb3b4da77df10b217c589f00dbae21d445bacf1
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
     |████████████████████████████████| 23.1 MB 1.4 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:
# pandas and numpy for data manipulation
import pandas as pd
import numpy as np


from tpot import TPOTClassifier

In [ ]:

#데이터 불러오기
from google.colab import drive 
drive.mount('/content/gdrive/')



Mounted at /content/gdrive/


In [ ]:
from scipy.stats import skew, kurtosis
Train = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(학습용데이터).csv', encoding='euc=kr')
Test = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(제출용데이터).csv', encoding='euc=kr')

A = ast.literal_eval(Train['Feature_Group_A'][0])
print(kurtosis(A))
print(skew(A))


NameError: ignored

In [ ]:
import pandas as pd
import ast
from scipy.stats import skew, kurtosis

#데이터 전처리

Train = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(학습용데이터).csv', encoding='euc=kr')
Test = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(제출용데이터).csv', encoding='euc=kr')

#데이터 프레임 생성

#테스트 피쳐
data = ast.literal_eval(Train['Feature_Group_C'][0])

A = ast.literal_eval(Train['Feature_Group_A'][0])

Askew = skew(A)

Akurtosis = kurtosis(A,fisher=True)

A = np.array(A)
A = np.std(A)



B = ast.literal_eval(Train['Feature_Group_B'][0])


Bskew = skew(B)

Bkurtosis = kurtosis(B,fisher=True)

B = np.array(B)
B = np.std(B)

printabledskew = skew(data['printabledist'])

printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

printabled = np.array(data['printabledist'])


printabled = np.std(printabled)



df_train_features = pd.DataFrame({
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                  'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'numstrings' : data['numstrings'],
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                  'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,                                 
                                  'printables' : data['printables'],
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ'],

                                  
},index=[0])
for i in range(1,len(Train)):
  data = ast.literal_eval(Train['Feature_Group_C'][i])

  A = ast.literal_eval(Train['Feature_Group_A'][i])

  Askew = skew(A)

  Akurtosis = kurtosis(A,fisher=True)

  A = np.array(A)
  A = np.std(A)



  B = ast.literal_eval(Train['Feature_Group_B'][i])


  Bskew = skew(B)

  Bkurtosis = kurtosis(B,fisher=True)

  B = np.array(B)
  B = np.std(B)

  printabledskew = skew(data['printabledist'])

  printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

  printabled = np.array(data['printabledist'])


  printabled = np.std(printabled)


  new_df ={
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                   'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'numstrings' : data['numstrings'],
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                   'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'printables' : data['printables'],
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
}
  new_df = pd.DataFrame(new_df,index=[i])

  df_train_features = pd.concat([df_train_features,new_df], sort=False)


  



#테스트 피처


data = ast.literal_eval(Test['Feature_Group_C'][0])

A = ast.literal_eval(Test['Feature_Group_A'][0])

Askew = skew(A)

Akurtosis = kurtosis(A,fisher=True)

A = np.array(A)
A = np.std(A)

B = ast.literal_eval(Test['Feature_Group_B'][0])

Bskew = skew(B)

Bkurtosis = kurtosis(B,fisher=True)

B = np.array(B)
B = np.std(B)


printabledskew = skew(data['printabledist'])

printabledkurtosis = kurtosis(data['printabledist'],fisher=True)


printabled = np.array(data['printabledist'])
printabled = np.std(printabled)



df_test_features = pd.DataFrame({
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                  'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'numstrings' : data['numstrings'],
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                 'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'printables' : data['printables'],
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
},index=[0])



for i in range(1,len(Test)):
  data = ast.literal_eval(Test['Feature_Group_C'][i])

  A = ast.literal_eval(Test['Feature_Group_A'][i])

  Askew = skew(A)

  Akurtosis = kurtosis(A,fisher=True)

  A = np.array(A)
  A = np.std(A)



  B = ast.literal_eval(Test['Feature_Group_B'][i])


  Bskew = skew(B)

  Bkurtosis = kurtosis(B,fisher=True)

  B = np.array(B)
  B = np.std(B)

  printabledskew = skew(data['printabledist'])

  printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

  printabled = np.array(data['printabledist'])


  printabled = np.std(printabled)


  new_df ={
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                   'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'numstrings' : data['numstrings'],
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                   'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'printables' : data['printables'],
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
}
  new_df = pd.DataFrame(new_df,index=[i])

  df_test_features = pd.concat([df_test_features,new_df], sort=False)




df_train_label = Train['label']




In [ ]:

df_train_features.style.hide_index()
df_test_features.style.hide_index()

# Convert to numpy arrays
training_features = np.array(df_train_features)
testing_features = np.array(df_test_features)






# Sklearn wants the labels as one-dimensional vectors

training_targets = np.array(df_train_label).reshape((-1,))


In [ ]:
# Create a tpot object with a few parameters
tpot = TPOTClassifier(generations=20,
                      population_size = 50,
                      verbosity = 2,
                      random_state = 42,
                      scoring = 'f1'
                      )

In [ ]:


tpot.fit(training_features, training_targets)

Optimization Progress:   0%|          | 0/1050 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 0.8872150471604467

Generation 2 - Current best internal CV score: 0.888003469949

Generation 3 - Current best internal CV score: 0.888003469949

Generation 4 - Current best internal CV score: 0.8944359927357525

Generation 5 - Current best internal CV score: 0.8944359927357525

Generation 6 - Current best internal CV score: 0.894684081989892

Generation 7 - Current best internal CV score: 0.894684081989892

Generation 8 - Current best internal CV score: 0.8966051111977993

Generation 9 - Current best internal CV score: 0.8966051111977993

Generation 10 - Current best internal CV score: 0.8966431465619575

Generation 11 - Current best internal CV score: 0.8966431465619575

Generation 12 - Current best internal CV score: 0.8978683849462374

Generation 13 - Current best internal CV score: 0.8978816985887697


TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: Rando

TPOTClassifier(generations=20, population_size=50, random_state=42,
               scoring='f1', verbosity=2)

In [ ]:
# Show the final model
print(tpot.fitted_pipeline_)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(include_bias=False)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=False, criterion='entropy',
                                        max_features=0.25, min_samples_leaf=3,
                                        min_samples_split=4,
                                        random_state=42))])


In [ ]:
# Export the pipeline as a python script file
tpot.export('tpot_exported_pipeline2.py')

In [ ]:
# Import file management
from google.colab import files
# Download the pipeline for local use
files.download('tpot_exported_pipeline2.py')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
tpot.export

<bound method TPOTBase.export of TPOTClassifier(generations=12, population_size=50, random_state=42,
               scoring='f1', verbosity=2)>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline, make_union
from tpot.builtins import StackingEstimator
from tpot.export_utils import set_param_recursive

# Average CV score on the training set was: 0.8917182991030398
exported_pipeline = make_pipeline(
    StackingEstimator(estimator=ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.7500000000000001, min_samples_leaf=2, min_samples_split=6, n_estimators=100)),
    RandomForestClassifier(bootstrap=True, criterion="gini", max_features=0.2, min_samples_leaf=8, min_samples_split=4, n_estimators=100)
)



In [ ]:
# Fix random state for all the steps in exported pipeline
set_param_recursive(exported_pipeline.steps, 'random_state', 42)

In [ ]:

exported_pipeline.fit(training_features, training_targets)


Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=ExtraTreesClassifier(criterion='entropy',
                                                                  max_features=0.7500000000000001,
                                                                  min_samples_leaf=2,
                                                                  min_samples_split=6,
                                                                  random_state=42))),
                ('randomforestclassifier',
                 RandomForestClassifier(max_features=0.2, min_samples_leaf=8,
                                        min_samples_split=4,
                                        random_state=42))])

In [ ]:
results= exported_pipeline.predict(training_features)

In [ ]:
print(results)

[1 1 0 ... 0 1 0]


In [ ]:
print(testing_features)

[[5.18805258e+03 1.14771417e+04 1.56000000e+03 ... 1.08000000e+02
  0.00000000e+00 5.00000000e+00]
 [3.61134583e+02 7.25278948e+03 1.66400000e+03 ... 1.00000000e+00
  0.00000000e+00 6.00000000e+00]
 [4.12520049e+03 6.89399650e+03 1.11100000e+03 ... 0.00000000e+00
  0.00000000e+00 4.00000000e+00]
 ...
 [7.08648314e+03 9.80985779e+03 4.52300000e+03 ... 3.70000000e+01
  0.00000000e+00 1.00000000e+00]
 [8.62528566e+03 1.66449631e+04 5.34700000e+03 ... 2.00000000e+00
  1.40000000e+01 4.00000000e+00]
 [2.10244063e+03 1.12426131e+04 5.06300000e+03 ... 1.00000000e+00
  1.00000000e+00 1.10000000e+01]]


In [ ]:
results= exported_pipeline.predict(testing_features)

3번째


In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures
from tpot.export_utils import set_param_recursive


# Average CV score on the training set was: 0.8978816985887697
exported_pipeline = make_pipeline(
    PolynomialFeatures(degree=2, include_bias=False, interaction_only=False),
    RandomForestClassifier(bootstrap=False, criterion="entropy", max_features=0.25, min_samples_leaf=3, min_samples_split=4, n_estimators=100)
)




In [ ]:
# Fix random state for all the steps in exported pipeline
set_param_recursive(exported_pipeline.steps, 'random_state', 42)


In [ ]:
exported_pipeline.fit(training_features, training_targets)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(include_bias=False)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=False, criterion='entropy',
                                        max_features=0.25, min_samples_leaf=3,
                                        min_samples_split=4,
                                        random_state=42))])

In [ ]:
results = exported_pipeline.predict(testing_features)

In [ ]:
test_label = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/세얼간이_1차.csv')

df_test_label = pd.DataFrame({'분석대상': Test['분석대상'][0],
                              '정답지' : results[0]
                                  
},index=[0])

for i in range(1,len(Test)):
  new_df_test_label = {'분석대상': Test['분석대상'][i],
                              '정답지' : int(results[i])
                                  
}
  new_df_test_label = pd.DataFrame(new_df_test_label,index=[i])

  df_test_label = pd.concat([df_test_label,new_df_test_label], sort=False)
df_test_label.to_csv('/content/gdrive/MyDrive/hoseo_AI/세얼간이_3_1차.csv',index=False)

실험

마지막

차원 축소 + SVM



In [ ]:
import pandas as pd
import ast
from scipy.stats import skew, kurtosis

#데이터 전처리

Train = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(학습용데이터).csv', encoding='euc=kr')
Test = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/AI_탐지트랙_대회(제출용데이터).csv', encoding='euc=kr')

#데이터 프레임 생성

#테스트 피쳐
data = ast.literal_eval(Train['Feature_Group_C'][0])

A = ast.literal_eval(Train['Feature_Group_A'][0])

Askew = skew(A)

Akurtosis = kurtosis(A,fisher=True)

A = np.array(A)
A = np.std(A)



B = ast.literal_eval(Train['Feature_Group_B'][0])


Bskew = skew(B)

Bkurtosis = kurtosis(B,fisher=True)

B = np.array(B)
B = np.std(B)

printabledskew = skew(data['printabledist'])

printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

printabled = np.array(data['printabledist'])


printabled = np.std(printabled)



df_train_features = pd.DataFrame({
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                  'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                  'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,                                 
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']

                                  
},index=[0])
for i in range(1,len(Train)):
  data = ast.literal_eval(Train['Feature_Group_C'][i])

  A = ast.literal_eval(Train['Feature_Group_A'][i])

  Askew = skew(A)

  Akurtosis = kurtosis(A,fisher=True)

  A = np.array(A)
  A = np.std(A)



  B = ast.literal_eval(Train['Feature_Group_B'][i])


  Bskew = skew(B)

  Bkurtosis = kurtosis(B,fisher=True)

  B = np.array(B)
  B = np.std(B)

  printabledskew = skew(data['printabledist'])

  printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

  printabled = np.array(data['printabledist'])


  printabled = np.std(printabled)


  new_df ={
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                   'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                   'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
}
  new_df = pd.DataFrame(new_df,index=[i])

  df_train_features = pd.concat([df_train_features,new_df], sort=False)


  



#테스트 피처


data = ast.literal_eval(Test['Feature_Group_C'][0])

A = ast.literal_eval(Test['Feature_Group_A'][0])

Askew = skew(A)

Akurtosis = kurtosis(A,fisher=True)

A = np.array(A)
A = np.std(A)

B = ast.literal_eval(Test['Feature_Group_B'][0])

Bskew = skew(B)

Bkurtosis = kurtosis(B,fisher=True)

B = np.array(B)
B = np.std(B)


printabledskew = skew(data['printabledist'])

printabledkurtosis = kurtosis(data['printabledist'],fisher=True)


printabled = np.array(data['printabledist'])
printabled = np.std(printabled)



df_test_features = pd.DataFrame({
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                  'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                 'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
},index=[0])



for i in range(1,len(Test)):
  data = ast.literal_eval(Test['Feature_Group_C'][i])

  A = ast.literal_eval(Test['Feature_Group_A'][i])

  Askew = skew(A)

  Akurtosis = kurtosis(A,fisher=True)

  A = np.array(A)
  A = np.std(A)



  B = ast.literal_eval(Test['Feature_Group_B'][i])


  Bskew = skew(B)

  Bkurtosis = kurtosis(B,fisher=True)

  B = np.array(B)
  B = np.std(B)

  printabledskew = skew(data['printabledist'])

  printabledkurtosis = kurtosis(data['printabledist'],fisher=True)

  printabled = np.array(data['printabledist'])


  printabled = np.std(printabled)


  new_df ={
                                  'Feature_Group_A': A,
                                  'Feature_Group_A_skew': Askew,
                                  'Feature_Group_A_kurtosis':Akurtosis,
                                  'Feature_Group_B': B,
                                   'Feature_Group_B_skew': Bskew,
                                  'Feature_Group_B_kurtosis':Bkurtosis,
                                  'avlength': data['avlength'],
                                  'printabledist':printabled,
                                   'printabledist_skew': printabledskew,
                                  'printabledist_kurtosis':printabledkurtosis,   
                                  'entropy': data['entropy'],
                                  'paths' : data['paths'],
                                  'urls' : data['urls'],
                                  'registry' : data['registry'],
                                  'MZ' : data['MZ']
}
  new_df = pd.DataFrame(new_df,index=[i])

  df_test_features = pd.concat([df_test_features,new_df], sort=False)




df_train_label = Train['label']

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline




In [ ]:
from sklearn.preprocessing import StandardScaler

df_train_features.style.hide_index()
df_test_features.style.hide_index()



train_df = StandardScaler().fit_transform(df_train_features)
test_df = StandardScaler().fit_transform(df_test_features)


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
#fit( )과 transform( ) 을 호출하여 PCA 변환 데이터 반환



pca.fit(train_df)
train = pca.transform(train_df)
print(train.shape)

pca.fit(test_df)
test = pca.transform(test_df)
print(test.shape)

print(test)
print(train)
#차원 축소 끝

(10000, 3)
(5000, 3)
[[ 1.43757338  0.50633332  1.10486311]
 [-3.00660219  2.41389801  0.9974405 ]
 [ 1.52702922 -1.24184843 -0.57354039]
 ...
 [-0.74463162 -0.69901187 -0.18909732]
 [-1.39262155  1.45603197  0.41935143]
 [ 1.32785322  4.1629335  -0.7708711 ]]
[[ 2.57366017 -0.43071638 -0.78754396]
 [ 1.13478847 -0.32824011  0.41737174]
 [-4.78147035  0.74383313 -0.21950086]
 ...
 [-0.08436695 -0.63296101 -0.76704223]
 [-1.00876099 -0.27082676 -0.74890614]
 [-2.79280309  0.44498018 -1.25472548]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


training_targets = np.array(df_train_label).reshape((-1,))

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(train, training_targets, test_size=0.2, random_state=42)

In [ ]:


scores = []
for thisC in [*range(1,100)]:
    svc=SVC(kernel='rbf',C=thisC)
    model=svc.fit(xtrain,ytrain)
    scoreTrain=model.score(xtrain,ytrain)
    scoreTest=model.score(xtest,ytest)
    print("rbf SVM : C:{}, training score:{:2f}, test score:{:2f}".format
          (thisC,scoreTrain, scoreTest))
    scores.append([scoreTrain, scoreTest])

rbf SVM : C:1, training score:0.726125, test score:0.721500
rbf SVM : C:2, training score:0.730750, test score:0.726500
rbf SVM : C:3, training score:0.730375, test score:0.726500
rbf SVM : C:4, training score:0.730375, test score:0.727500
rbf SVM : C:5, training score:0.730750, test score:0.728000
rbf SVM : C:6, training score:0.738000, test score:0.735000
rbf SVM : C:7, training score:0.745875, test score:0.745500
rbf SVM : C:8, training score:0.746750, test score:0.746500
rbf SVM : C:9, training score:0.748000, test score:0.748500
rbf SVM : C:10, training score:0.747875, test score:0.748000
rbf SVM : C:11, training score:0.747625, test score:0.747000
rbf SVM : C:12, training score:0.748125, test score:0.748500
rbf SVM : C:13, training score:0.747375, test score:0.748000
rbf SVM : C:14, training score:0.748750, test score:0.748000
rbf SVM : C:15, training score:0.748625, test score:0.747500
rbf SVM : C:16, training score:0.748875, test score:0.747000
rbf SVM : C:17, training score:0.

In [ ]:
best = 0.776000
getc = 0
getg = 0
for thisC in [*range(22,40)]:
  for j in range(1,100):
    svc=SVC(kernel='rbf',C=thisC, gamma= j )
    model=svc.fit(xtrain,ytrain)
    scoreTrain=model.score(xtrain,ytrain)
    scoreTest=model.score(xtest,ytest)
    print("rbf SVM : C:{}, g:{} training score:{:2f}, test score:{:2f}".format
          (thisC,j,scoreTrain, scoreTest))
    if best < scoreTest:
      best = scoreTest
      getc = thisC
      getg = j

    

rbf SVM : C:22, g:1 training score:0.778000, test score:0.759500
rbf SVM : C:22, g:2 training score:0.795875, test score:0.765500
rbf SVM : C:22, g:3 training score:0.809875, test score:0.753500
rbf SVM : C:22, g:4 training score:0.825500, test score:0.758500
rbf SVM : C:22, g:5 training score:0.839000, test score:0.767500
rbf SVM : C:22, g:6 training score:0.850000, test score:0.772000
rbf SVM : C:22, g:7 training score:0.856625, test score:0.768500
rbf SVM : C:22, g:8 training score:0.860125, test score:0.762000
rbf SVM : C:22, g:9 training score:0.868125, test score:0.759000
rbf SVM : C:22, g:10 training score:0.873375, test score:0.756000
rbf SVM : C:22, g:11 training score:0.876750, test score:0.758500
rbf SVM : C:22, g:12 training score:0.880625, test score:0.759000
rbf SVM : C:22, g:13 training score:0.884625, test score:0.754500
rbf SVM : C:22, g:14 training score:0.888875, test score:0.753000
rbf SVM : C:22, g:15 training score:0.892000, test score:0.752000
rbf SVM : C:22, g:1

KeyboardInterrupt: ignored

rbf SVM : C:6, g:8 training score:0.846375, test score:0.775500

In [ ]:
before = 0
now =  best

bc = 0
bg = 0
 

In [ ]:
svc=SVC(kernel='rbf',C=6, gamma= 7.9 )
model=svc.fit(xtrain,ytrain)
scoreTrain=model.score(xtrain,ytrain)
scoreTest=model.score(xtest,ytest)
print("rbf SVM : C:{}, g:{} training score:{:2f}, test score:{:2f}".format
          (1,1,scoreTrain, scoreTest))

rbf SVM : C:1, g:1 training score:0.846250, test score:0.776000


rbf SVM : C:1, g:1 training score:0.846250, test score:0.776000

In [ ]:
svc=SVC(kernel='rbf',C=6, gamma= 7.9 )
model=svc.fit(train,training_targets)


In [ ]:
results = model.predict(test)

In [ ]:
print(results)

[1 1 1 ... 0 0 1]


In [ ]:
t_label = pd.read_csv('/content/gdrive/MyDrive/hoseo_AI/세얼간이_1차.csv')

df_test_label = pd.DataFrame({'분석대상': Test['분석대상'][0],
                              '정답지' : results[0]
                                  
},index=[0])

for i in range(1,len(Test)):
  new_df_test_label = {'분석대상': Test['분석대상'][i],
                              '정답지' : int(results[i])
                                  
}
  new_df_test_label = pd.DataFrame(new_df_test_label,index=[i])

  df_test_label = pd.concat([df_test_label,new_df_test_label], sort=False)
df_test_label.to_csv('/content/gdrive/MyDrive/hoseo_AI/세얼간이4차.csv',index=False)